// <auto-generated />
using System;
using ChroniclesOfFate.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChroniclesOfFate.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260202133300_RemoveStorybookRarity")]
    partial class RemoveStorybookRarity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.BattleLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BattleNarrative")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("CharacterPowerAtBattle")
                        .HasColumnType("int");

                    b.Property<int>("EnemyId")
                        .HasColumnType("int");

                    b.Property<int>("EnemyPowerAtBattle")
                        .HasColumnType("int");

                    b.Property<int>("EnergySpent")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceGained")
                        .HasColumnType("int");

                    b.Property<int>("GoldGained")
                        .HasColumnType("int");

                    b.Property<int>("HealthLost")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReputationGained")
                        .HasColumnType("int");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("RoundsCount")
                        .HasColumnType("int");

                    b.Property<int>("Turn")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("EnemyId");

                    b.ToTable("BattleLogs");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Agility")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("Charisma")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentEnergy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<int>("CurrentHealth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<int>("CurrentMonth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("CurrentYear")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Endurance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("Level")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("Luck")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("MaxEnergy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<int>("MaxHealth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Reputation")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(10);

                    b.Property<int>("TotalTurns")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId")
                        .IsUnique();

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.CharacterStorybook", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("StorybookId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EquippedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SlotPosition")
                        .HasColumnType("int");

                    b.HasKey("CharacterId", "StorybookId");

                    b.HasIndex("StorybookId");

                    b.ToTable("CharacterStorybooks");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.Enemy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abilities")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ActiveSeasons")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Agility")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("DifficultyTier")
                        .HasColumnType("int");

                    b.Property<int>("Endurance")
                        .HasColumnType("int");

                    b.Property<string>("EnemyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ExperienceReward")
                        .HasColumnType("int");

                    b.Property<int>("GoldReward")
                        .HasColumnType("int");

                    b.Property<int>("Health")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LootTable")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReputationReward")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Enemies");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.EventChoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgilityChange")
                        .HasColumnType("int");

                    b.Property<int>("CharismaChange")
                        .HasColumnType("int");

                    b.Property<int>("CheckDifficulty")
                        .HasColumnType("int");

                    b.Property<int?>("CheckStat")
                        .HasColumnType("int");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("EnduranceChange")
                        .HasColumnType("int");

                    b.Property<int>("EnergyChange")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceChange")
                        .HasColumnType("int");

                    b.Property<int>("FailureAgilityChange")
                        .HasColumnType("int");

                    b.Property<int>("FailureCharismaChange")
                        .HasColumnType("int");

                    b.Property<string>("FailureDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("FailureEnduranceChange")
                        .HasColumnType("int");

                    b.Property<int>("FailureEnergyChange")
                        .HasColumnType("int");

                    b.Property<int>("FailureGoldChange")
                        .HasColumnType("int");

                    b.Property<int>("FailureHealthChange")
                        .HasColumnType("int");

                    b.Property<int>("FailureIntelligenceChange")
                        .HasColumnType("int");

                    b.Property<int>("FailureLuckChange")
                        .HasColumnType("int");

                    b.Property<int>("FailureReputationChange")
                        .HasColumnType("int");

                    b.Property<int>("FailureStrengthChange")
                        .HasColumnType("int");

                    b.Property<int?>("FollowUpEventId")
                        .HasColumnType("int");

                    b.Property<int>("GoldChange")
                        .HasColumnType("int");

                    b.Property<int>("HealthChange")
                        .HasColumnType("int");

                    b.Property<int>("IntelligenceChange")
                        .HasColumnType("int");

                    b.Property<int>("LuckChange")
                        .HasColumnType("int");

                    b.Property<int>("RandomEventId")
                        .HasColumnType("int");

                    b.Property<int>("ReputationChange")
                        .HasColumnType("int");

                    b.Property<string>("ResultDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("StatRequirements")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("StrengthChange")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TriggerBattleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RandomEventId");

                    b.ToTable("EventChoices");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.GameEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<bool?>("CheckSucceeded")
                        .HasColumnType("bit");

                    b.Property<int?>("ChosenOptionId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RandomEventId")
                        .HasColumnType("int");

                    b.Property<string>("ResultSummary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("RollResult")
                        .HasColumnType("int");

                    b.Property<int>("Turn")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ChosenOptionId");

                    b.HasIndex("RandomEventId");

                    b.ToTable("GameEvents");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.GameSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndingType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("FinalScore")
                        .HasColumnType("int");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId1");

                    b.ToTable("GameSessions");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.MessageLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("StatChangesJson")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId", "CreatedAt");

                    b.ToTable("MessageLogEntries");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.RandomEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BaseProbability")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("OutcomeType")
                        .HasColumnType("int");

                    b.Property<int>("Rarity")
                        .HasColumnType("int");

                    b.Property<string>("StatRequirements")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("StorybookId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TriggerActions")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TriggerSeasons")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StorybookId");

                    b.ToTable("RandomEvents");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.Storybook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgilityBonus")
                        .HasColumnType("int");

                    b.Property<int>("CharismaBonus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EnduranceBonus")
                        .HasColumnType("int");

                    b.Property<double>("EventTriggerChance")
                        .HasColumnType("float");

                    b.Property<int?>("GameSessionId")
                        .HasColumnType("int");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IntelligenceBonus")
                        .HasColumnType("int");

                    b.Property<bool>("IsUnlockable")
                        .HasColumnType("bit");

                    b.Property<int>("LuckBonus")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StrengthBonus")
                        .HasColumnType("int");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UnlockCondition")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("GameSessionId");

                    b.ToTable("Storybooks");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.TrainingScenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseStatGain")
                        .HasColumnType("int");

                    b.Property<double>("BonusChance")
                        .HasColumnType("float");

                    b.Property<string>("BonusSeasons")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BonusStatGain")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EnergyCost")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceGain")
                        .HasColumnType("int");

                    b.Property<double>("FailureChance")
                        .HasColumnType("float");

                    b.Property<int>("FailureHealthPenalty")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PrimaryStat")
                        .HasColumnType("int");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int");

                    b.Property<double>("SeasonalBonusMultiplier")
                        .HasColumnType("float");

                    b.Property<int?>("SecondaryStat")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryStatGain")
                        .HasColumnType("int");

                    b.Property<int?>("TertiaryStat")
                        .HasColumnType("int");

                    b.Property<int>("TertiaryStatGain")
                        .HasColumnType("int");

                    b.Property<string>("TrainingNarrative")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("TrainingScenarios");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Player");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.BattleLog", b =>
                {
                    b.HasOne("ChroniclesOfFate.Core.Entities.Character", "Character")
                        .WithMany("BattleHistory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChroniclesOfFate.Core.Entities.Enemy", "Enemy")
                        .WithMany()
                        .HasForeignKey("EnemyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Enemy");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.Character", b =>
                {
                    b.HasOne("ChroniclesOfFate.Core.Entities.GameSession", "GameSession")
                        .WithOne("Character")
                        .HasForeignKey("ChroniclesOfFate.Core.Entities.Character", "GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.CharacterStorybook", b =>
                {
                    b.HasOne("ChroniclesOfFate.Core.Entities.Character", "Character")
                        .WithMany("EquippedStorybooks")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChroniclesOfFate.Core.Entities.Storybook", "Storybook")
                        .WithMany("CharacterStorybooks")
                        .HasForeignKey("StorybookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Storybook");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.EventChoice", b =>
                {
                    b.HasOne("ChroniclesOfFate.Core.Entities.RandomEvent", "RandomEvent")
                        .WithMany("Choices")
                        .HasForeignKey("RandomEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RandomEvent");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.GameEvent", b =>
                {
                    b.HasOne("ChroniclesOfFate.Core.Entities.Character", "Character")
                        .WithMany("EventHistory")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ChroniclesOfFate.Core.Entities.EventChoice", "ChosenOption")
                        .WithMany()
                        .HasForeignKey("ChosenOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ChroniclesOfFate.Core.Entities.RandomEvent", "RandomEvent")
                        .WithMany()
                        .HasForeignKey("RandomEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("ChosenOption");

                    b.Navigation("RandomEvent");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.GameSession", b =>
                {
                    b.HasOne("ChroniclesOfFate.Core.Entities.User", null)
                        .WithMany("GameSessions")
                        .HasForeignKey("UserId1");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.MessageLogEntry", b =>
                {
                    b.HasOne("ChroniclesOfFate.Core.Entities.GameSession", "GameSession")
                        .WithMany("MessageLog")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.RandomEvent", b =>
                {
                    b.HasOne("ChroniclesOfFate.Core.Entities.Storybook", "Storybook")
                        .WithMany("Events")
                        .HasForeignKey("StorybookId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Storybook");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.Storybook", b =>
                {
                    b.HasOne("ChroniclesOfFate.Core.Entities.GameSession", null)
                        .WithMany("UnlockedStorybooks")
                        .HasForeignKey("GameSessionId");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.Character", b =>
                {
                    b.Navigation("BattleHistory");

                    b.Navigation("EquippedStorybooks");

                    b.Navigation("EventHistory");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.GameSession", b =>
                {
                    b.Navigation("Character");

                    b.Navigation("MessageLog");

                    b.Navigation("UnlockedStorybooks");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.RandomEvent", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.Storybook", b =>
                {
                    b.Navigation("CharacterStorybooks");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("ChroniclesOfFate.Core.Entities.User", b =>
                {
                    b.Navigation("GameSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
